SELECT MAX(PERSON.NETWORTHBI) FROM PERSON;
SELECT MIN(INDUSTRY.INCOMESBI) FROM PERSON JOIN INDUSTRY ON PERSON.INDUSTRY_IDINDUSTRY = INDUSTRY.IDINDUSTRY;

SELECT AVG(DISTINCT COUNTRY.POPULACEMI), AVG(DISTINCT UNIVERSITY.OVERALLSCORE) FROM COUNTRY JOIN UNIVERSITY ON COUNTRY.IDCOUNTRY = UNIVERSITY.COUNTRY_IDCOUNTRY
WHERE UNIVERSITY.OVERALLSCORE > 75;

SELECT COUNT(DISTINCT COUNTRY.IDCOUNTRY)AS C, COUNT(DISTINCT UNIVERSITY.IDUNIVERSITY)AS U FROM COUNTRY JOIN UNIVERSITY ON COUNTRY.IDCOUNTRY = UNIVERSITY.COUNTRY_IDCOUNTRY
WHERE UNIVERSITY.OVERALLSCORE > 75;

SELECT COUNT(DISTINCT COUNTRY.IDCOUNTRY) AS C, COUNT(DISTINCT UNIVERSITY.IDUNIVERSITY) AS U FROM COUNTRY JOIN UNIVERSITY ON COUNTRY.IDCOUNTRY = UNIVERSITY.COUNTRY_IDCOUNTRY
WHERE UNIVERSITY.OVERALLSCORE > 75 AND UNIVERSITY.TEACHINGSCORE > 75;

SELECT COUNTRY.NAME, UNIVERSITY.NAME FROM COUNTRY JOIN UNIVERSITY ON COUNTRY.IDCOUNTRY = UNIVERSITY.COUNTRY_IDCOUNTRY
WHERE UNIVERSITY.OVERALLSCORE > 75  AND UNIVERSITY.TEACHINGSCORE > 75;

SELECT PERSON.FULLNAME, PERSON.NETWORTHBI FROM PERSON JOIN INDUSTRY ON PERSON.INDUSTRY_IDINDUSTRY = INDUSTRY.IDINDUSTRY
WHERE INDUSTRY.INCOMESBI > 1000
ORDER BY PERSON.NETWORTHBI DESC;

SELECT * FROM COUNTRY ORDER BY POPULACEMI DESC;